### ISSUE TITLE
Further usage instructions expected

### ISSUE THREAD

**Issue by HinT786** [HilscherAutomation/meta-hilscher-drivers#1]
Dear developers,
Can you please provide more instructions on how to properly include libcifx into a yocto image?

So far I have enabled the necessary kernel options in the menuconfig (namely uio_netx and cifx), cloned the repo and added IMAGE_INSTALL += "libcifx" to the local.conf. Unfortunately the QA-errors "dev-so" and "dev-deps" appear. I assume it is reasonable to include these as INSANE_SKIP:libcifx += "dev-so dev-deps".
But unfortunately the bitbake-results don't appear in the final image. Am I missing some necessary steps?

**Comment by MTrensch-hilscher** [comment]
I cannot reproduce your problem using the scarthgap poky branch with meta-hilscher-drivers ([e731f7f1f386c401597d2dcc6bc712d94ad39086](https://github.com/HilscherAutomation/meta-hilscher-drivers/tree/e731f7f1f386c401597d2dcc6bc712d94ad39086)) while building core-image-minimal, using the default poky distro.

There were neither QA errors nor missing libraries in the image:

```
$ tail conf/local.conf
#
#BB_SERVER_TIMEOUT = "60"

# CONF_VERSION is increased each time build/conf/ changes incompatibly and is used to
# track the version of this file when it was generated. This can safely be ignored if
# this doesn't mean anything to you.
CONF_VERSION = "2"

IMAGE_INSTALL:append = " libcifx"
KERNEL_EXTRA_FEATURES:append = " features/uio/uio.scc"
```

```
$ find core-image-minimal/1.0/rootfs/ -name '*cifx*' -o -iname '*netx*'
core-image-minimal/1.0/rootfs/lib/modules/6.6.35-yocto-standard/kernel/drivers/uio/uio_netx.ko
core-image-minimal/1.0/rootfs/lib/udev/rules.d/80-hilscher-cifxeth.rules
core-image-minimal/1.0/rootfs/lib/udev/rules.d/80-hilscher-netx.rules
core-image-minimal/1.0/rootfs/opt/cifx
core-image-minimal/1.0/rootfs/opt/cifx/NETX50-BSL.bin
core-image-minimal/1.0/rootfs/opt/cifx/NETX10-BSL.bin
core-image-minimal/1.0/rootfs/opt/cifx/NETX52-BSL.bin
core-image-minimal/1.0/rootfs/opt/cifx/NETX100-BSL.bin
core-image-minimal/1.0/rootfs/opt/cifx/NETX51-BSL.bin
core-image-minimal/1.0/rootfs/usr/lib/libcifx.so.3.0.0
core-image-minimal/1.0/rootfs/usr/lib/libcifx.so.3
core-image-minimal/1.0/rootfs/usr/sbin/cifxeth
```

But I added a short hint on using it, see 8d5c7a4177ee0aa386e75edd951ebe61cdfd1838

**Comment by HinT786** [comment]
Thank you @MTrensch-hilscher, your hint helped to resolve the problem.
The issue was caused by some lines that enable multilib, which is now uncommented:

```
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "x86"
```

Moreover, `IMAGE_INSTALL:append = "libcifx"` had to be used instead of `IMAGE_INSTALL += "libcifx"`.
